"""
generate_report.py -- Generate Word report comparing original vs reconstructed
KM curves, with survival statistics and hazard rate plots.

Usage:
    python generate_report.py <digitized.json> <ipd_combined.csv> <output_dir>

Outputs (written to output_dir):
    reconstruction_report.docx
    km_comparison.png
    hazard_rate.png
"""

import json
import sys
import os
import shutil
import subprocess
import numpy as np
import pandas as pd
from docx import Document
from docx.shared import Inches, Pt
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.enum.table import WD_TABLE_ALIGNMENT


def load_inputs(json_path, ipd_path):
    with open(json_path) as f:
        dat = json.load(f)
    ipd = pd.read_csv(ipd_path)
    return dat, ipd


# ---- R discovery -----------------------------------------------------------

def _find_rscript():
    if os.environ.get("RSCRIPT_PATH"):
        return os.environ["RSCRIPT_PATH"]
    found = shutil.which("Rscript")
    if found:
        return found
    candidates = [
        r"C:\Program Files\R\R-4.4.2\bin\Rscript.exe",
        r"C:\Program Files\R\R-4.4.1\bin\Rscript.exe",
        r"C:\Program Files\R\R-4.3.3\bin\Rscript.exe",
        "/usr/local/bin/Rscript",
        "/usr/bin/Rscript",
    ]
    for path in candidates:
        if os.path.isfile(path):
            return path
    raise RuntimeError(
        "Rscript not found. Install R and either add it to PATH "
        "or set the RSCRIPT_PATH environment variable."
    )

RSCRIPT = _find_rscript()

# ---- Plots (generated by R) -----------------------------------------------

PLOT_SCRIPT = os.path.join(os.path.dirname(__file__), "plot_km_hazard.R")


def generate_r_plots(json_path, ipd_path, output_dir):
    """Call plot_km_hazard.R to generate KM comparison and hazard rate plots."""
    cmd = [RSCRIPT, PLOT_SCRIPT, json_path, ipd_path, output_dir]
    result = subprocess.run(cmd, capture_output=True, text=True)
    print(result.stdout, end="")
    if result.returncode != 0:
        print(result.stderr)
        raise RuntimeError(f"R plotting script failed (exit {result.returncode})")
    km_path = os.path.join(output_dir, "km_comparison.png")
    hz_path = os.path.join(output_dir, "hazard_rate.png")
    return km_path, hz_path


# ---- Survival statistics --------------------------------------------------

STATS_SCRIPT = os.path.join(os.path.dirname(__file__), "survival_stats.R")


def compute_survival_stats(ipd_path, report_times):
    """Compute median and survival rates per arm via R's survival package."""
    times_str = ",".join(str(int(t)) for t in report_times if t > 0)
    result = subprocess.run(
        [RSCRIPT, STATS_SCRIPT, ipd_path, times_str],
        capture_output=True, text=True
    )
    if result.returncode != 0:
        print(result.stderr)
        raise RuntimeError("R survival stats failed")

    # Parse R output
    ipd = pd.read_csv(ipd_path)
    arms = ipd["arm"].unique()
    rows = [{"Statistic": "Median (months)"}]
    for t in report_times:
        if t == 0:
            continue
        rows.append({"Statistic": f"Survival at {int(t)} mo"})

    for line in result.stdout.strip().split("\n"):
        parts = line.strip().split()
        if not parts:
            continue
        if "MEDIAN" in parts:
            idx = parts.index("MEDIAN")
            arm = " ".join(parts[:idx])
            val = parts[idx + 1]
            rows[0][arm] = val
        elif "SURV" in parts:
            idx = parts.index("SURV")
            arm = " ".join(parts[:idx])
            t_val = int(parts[idx + 1])
            surv_val = parts[idx + 2]
            for r in rows:
                if r["Statistic"] == f"Survival at {t_val} mo":
                    r[arm] = f"{surv_val}%"

    return pd.DataFrame(rows)


# ---- Word report -----------------------------------------------------------

def generate_docx(dat, ipd, km_path, hz_path, stats_df, output_dir):
    doc = Document()

    # Title
    title = doc.add_heading("KM Curve Reconstruction Report", level=1)
    doc.add_paragraph(f"Source: {dat.get('source_image', 'N/A')}")
    doc.add_paragraph("")

    # 1. KM comparison
    doc.add_heading("1. KM Curve Comparison", level=2)
    doc.add_paragraph(
        "Side-by-side comparison of the digitized KM curves (left) and the "
        "reconstructed KM curves from individual patient data (right)."
    )
    doc.add_picture(km_path, width=Inches(7.0))
    doc.add_paragraph("")

    # 2. Survival statistics table
    doc.add_heading("2. Survival Statistics", level=2)
    doc.add_paragraph(
        "Median survival and survival rates at key timepoints, "
        "estimated from reconstructed IPD."
    )

    # Build table
    n_rows = len(stats_df) + 1  # +1 for header
    n_cols = len(stats_df.columns)
    table = doc.add_table(rows=n_rows, cols=n_cols, style="Light Shading Accent 1")
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    # Header row
    for j, col_name in enumerate(stats_df.columns):
        cell = table.rows[0].cells[j]
        cell.text = col_name
        for p in cell.paragraphs:
            p.alignment = WD_ALIGN_PARAGRAPH.CENTER
            for run in p.runs:
                run.bold = True
                run.font.size = Pt(9)

    # Data rows
    for i, row in stats_df.iterrows():
        for j, val in enumerate(row):
            cell = table.rows[i + 1].cells[j]
            cell.text = str(val)
            for p in cell.paragraphs:
                p.alignment = WD_ALIGN_PARAGRAPH.CENTER if j > 0 else WD_ALIGN_PARAGRAPH.LEFT
                for run in p.runs:
                    run.font.size = Pt(9)
                    if j == 0:
                        run.bold = True

    doc.add_paragraph("")

    # 3. Hazard rate
    doc.add_heading("3. Hazard Rate Over Time", level=2)
    doc.add_paragraph(
        "Smoothed hazard rate estimated using B-spline smoothing "
        "(bshazard). Truncated where any arm drops below 20% at risk."
    )
    doc.add_picture(hz_path, width=Inches(6.0))

    # Appendix: Original image
    orig_path = dat.get("image_path")
    if orig_path and os.path.exists(orig_path):
        doc.add_paragraph("")
        doc.add_heading("Appendix: Original KM Plot", level=2)
        doc.add_picture(orig_path, width=Inches(6.0))

    report_path = os.path.join(output_dir, "reconstruction_report.docx")
    doc.save(report_path)
    print(f"Report saved: {report_path}")
    return report_path


# ---- Main ------------------------------------------------------------------

def main():
    if len(sys.argv) < 4:
        print("Usage: python generate_report.py <digitized.json> <ipd_combined.csv> <output_dir>")
        sys.exit(1)

    json_path = sys.argv[1]
    ipd_path = sys.argv[2]
    output_dir = sys.argv[3]
    os.makedirs(output_dir, exist_ok=True)

    dat, ipd = load_inputs(json_path, ipd_path)
    arms = ipd["arm"].unique()
    print(f"IPD: {len(ipd)} patients, {ipd['event'].sum():.0f} events across {len(arms)} arms")

    # Report timepoints from number-at-risk or default every 12 months
    nar = dat.get("number_at_risk")
    report_times = nar["times"] if nar else list(range(0, int(dat["x_axis"]["range"][1]) + 1, 12))

    km_path, hz_path = generate_r_plots(json_path, ipd_path, output_dir)
    stats_df = compute_survival_stats(ipd_path, report_times)

    # Prepend N and Events rows
    n_row = {"Statistic": "N (patients)"}
    ev_row = {"Statistic": "Events, n (%)"}
    for arm in ipd["arm"].unique():
        arm_ipd = ipd[ipd["arm"] == arm]
        n = len(arm_ipd)
        ev = int(arm_ipd["event"].sum())
        n_row[arm] = str(n)
        ev_row[arm] = f"{ev} ({100*ev/n:.1f}%)"
    stats_df = pd.concat([pd.DataFrame([n_row, ev_row]), stats_df], ignore_index=True)

    generate_docx(dat, ipd, km_path, hz_path, stats_df, output_dir)


if __name__ == "__main__":
    main()
